### PR TITLE
I am interested in using your game on my website. Could you add a license file like the MIT one in this pull request so I know how you want your software used?

### PR DESCRIPTION
**Pull request by jpbida**

### CODE REVIEW

**Comment by tobernguyen** [comment]
Done. Thanks for asking.

**Comment by tobernguyen** [comment]
My mistake. Can you create the pull request again? I will accept that.

**Comment by jpbida** [comment]
You can use Github's license tool. Click "Add file" , type "license" for
the file name and you will see a select box appear with a choice of
licenses. Thanks!

**Comment by tobernguyen** [comment]
@jpbida updated, feel free to use 😄

**Pull request closed without merging**
